baseURL = "https://hivegps.netlify.app/"
languageCode = "pt-br"
title = "Portfólio da Equipe"

# 1. O NOVO TEMA
theme = "hugo-brewm"

[params]
  customCSS = ["css/custom.css"]

# 2. O seu Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "integrantes"
    name = "Integrantes"
    url = "/equipe/"
    weight = 10

  [[menu.main]]
    identifier = "sobre"
    name = "Sobre o Projeto"
    url = "/sobre/"
    weight = 20

# 3. Configuração de Markdown (Mínima)
# Precisamos disto para os blocos de código no seu "Guia do Hugo"
[markup]
  [markup.highlight]
    codeFences = true