baseURL = "https://example.org/"
languageCode = "en-us"
title = "Portf贸lio da Equipe"
theme = "PaperMod"

[params]
    author = "Lizandra, Bruna e Gabriel"
    description = "O portf贸lio de projetos da nossa equipe. "
    
    # Configura莽茫o do Modo Dark/Light
    defaultTheme = "auto" 
    disableThemeToggle = false

    # Isto EST AGORA DESATIVADO:
    # [params.homeInfoParams]
    #    Title = "Ol谩, n贸s somos a Equipe "
    #    Content = "Bem-vindo ao nosso portf贸lio digital. Somos um time de 3 alunos (Lizandra, Bruna e Gabriel) a construir projetos incr铆veis com Hugo e GitLab. Veja os nossos perfis abaixo!"

    # Links para redes sociais (pode p么r o do grupo ou da Lizandra)
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/LizandraAbelha"

[menu]
  # Isto cria o menu principal
  [[menu.main]]
    identifier = "equipe"
    name = "Integrantes"
    url = "/equipe/"
    weight = 10
  [[menu.main]]
    identifier = "sobre"
    name = "Sobre o Projeto"
    url = "/sobre/"
    weight = 20